src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @Assert\NotBlank(message="Veuillez donner un nom à votre sortie")
     * @Assert\Length(
     *     min=2,
     *     max=50,
     *     minMessage="Le nom de l'évènement doit être d'au moins 2 caractères",
     *     maxMessage="Le nom de l'évènement pas excéder 50 caractères")
     * @ORM\Column(type="string", length=100)
     */
    private ?string $name;

    /**
     * @Assert\GreaterThan("today", message="Veuillez saisir une date postérieure à la date actuelle")
     * @Assert\GreaterThan("+1 hour", message="Votre sortie doit se dérouler au minimum 1h après la date actuelle")
     * @Assert\NotBlank(message="Veuillez renseigner la date et l'heure de votre sortie")
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $dateTimeStart;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $dateTimeEnd;

    /**
     * @Assert\LessThan(propertyPath="dateTimeStart", message="Veuillez saisir une date de fin d'inscription avant la date et l'heure de début de votre sortie")
     * @Assert\GreaterThan("now", message="La date de limite d'inscription ne peut pas être inférieure à la date d'aujourd'hui")
     * @Assert\NotBlank(message="Veuillez renseigner une date limite d'inscription")
     * @ORM\Column(type="datetime")
     */
    private ?DateTimeInterface $registrationDeadline;

    /**
     * @Assert\NotBlank(message="Veuillez renseigner un nombre maximum de participants")
     * @Assert\GreaterThan(0, message="Le minimum de participants est de 1")
     * @Assert\LessThan(7, message=" Le nombre maximum de 6 participants doit être respecté")
     *
     * @ORM\Column(type="integer")
     */
    private ?int $maxNumberParticipants;

    /**
     * @Assert\NotBlank(message="Veuillez renseigner une description à votre sortie")
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $description;

    /**
     * @ORM\ManyToOne(targetEntity=Place::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Place $place;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Status $status;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Campus $campus;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="events")
     */
    private $participants;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="organisedEvents")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $organiser;

    //TO DO mettre une durée minimum et maximum
    /**
     * @Assert\NotBlank(message="Veuillez renseigner une durée pour votre sortie")
     * @Assert\GreaterThan(15, message="La sortie doit au moins durer 15 minutes")
     * @Assert\LessThan(1440, message="La sortie ne peut pas excéder 24h")
     * @ORM\Column(type="integer")
     */
    private ?int $duration;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $cancellation_reason;


    public function __construct()
    {
        $this->participants = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateTimeStart(): ?DateTimeInterface
    {
        return $this->dateTimeStart;
    }

    public function setDateTimeStart(?DateTimeInterface $dateTimeStart): self
    {
        $this->dateTimeStart = $dateTimeStart;

        return $this;
    }

    public function getDateTimeEnd(): ?DateTimeInterface
    {
        return $this->dateTimeEnd;
    }

    public function setDateTimeEnd(DateTimeInterface $dateTimeEnd): self
    {
        $this->dateTimeEnd = $dateTimeEnd;

        return $this;
    }

    public function getRegistrationDeadline(): ?DateTimeInterface
    {
        return $this->registrationDeadline;
    }

    public function setRegistrationDeadline(?DateTimeInterface $RegistrationDeadline): self
    {
        $this->registrationDeadline = $RegistrationDeadline;

        return $this;
    }

    public function getMaxNumberParticipants(): ?int
    {
        return $this->maxNumberParticipants;
    }

    public function setMaxNumberParticipants(int $maxNumberParticipants): self
    {
        $this->maxNumberParticipants = $maxNumberParticipants;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPlace(): ?Place
    {
        return $this->place;
    }

    public function setPlace(?Place $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->campus;
    }

    public function setCampus(?Campus $campus): self
    {
        $this->campus = $campus;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getParticipants(): Collection
    {
        return $this->participants;
    }

    public function addParticipant(User $participant): self
    {
        if (!$this->participants->contains($participant)) {
            $this->participants[] = $participant;
        }

        return $this;
    }

    public function removeParticipant(User $participant): self
    {
        $this->participants->removeElement($participant);

        return $this;
    }

    public function getOrganiser(): ?User
    {
        return $this->organiser;
    }

    public function setOrganiser(?User $organiser): self
    {
        $this->organiser = $organiser;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getCancellationReason(): ?string
    {
        return $this->cancellation_reason;
    }

    public function setCancellationReason(?string $cancellation_reason): self
    {
        $this->cancellation_reason = $cancellation_reason;

        return $this;
    }

}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\Status;
use App\Entity\User;
use App\Form\EventCancellationType;
use App\Form\EventType;
use App\Repository\CityRepository;
use App\Repository\EventRepository;
use App\Repository\PlaceRepository;
use App\Repository\StatusRepository;
use App\Utils\Constantes;
use App\Utils\FunctionsStatus;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Utils\DateTimeHandler;

class EventController extends AbstractController
{
    const WARNING_EVENT_NOT_AUTHORIZED = "Vous n'êtes pas autorisé à réaliser cette action";
    const WARNING_EVENT_WRONG_STATUS = "Action impossible, statut de la sortie incohérent";
    const SUCCESS_EVENT_PUBLISHED = "La sortie a été publiée avec succès";
    const WARNING_EVENT_WRONG_PLACE = "Le lieu doit être renseigné.";


    /**
     * Permet de visualiser les informations liées à un évenement
     * @Route ("/evenement/consulter/{id}", name="event_view")
     * @param int $id
     * @param EventRepository $eventRepository
     * @return Response
     */
    public function view(int $id,
                         EventRepository $eventRepository): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $foundEvent = $eventRepository->find($id);
        $foundEventStatusName = $foundEvent->getStatus()->getName();

        if (!$foundEvent ||
            ($foundEventStatusName == Constantes::CREATED and
                $foundEvent->getOrganiser() !== $user ||
                $foundEventStatusName == Constantes::ARCHIVED
            )
        ) {
            throw $this->createNotFoundException("Cet évenement n'existe pas");
        } else {
            $foundParticipants = $foundEvent->getParticipants();
            return $this->render('event/view.html.twig', [
                'foundEvent' => $foundEvent,
                'foundParticipants' => $foundParticipants
            ]);
        }
    }

    /**
     * Permet de créer un évènement
     * @Route ("/evenement/creer/", name="event_creation")
     * @param Request $request
     * @param EntityManagerInterface $entityManager
     * @param StatusRepository $statusRepository
     * @return RedirectResponse|Response
     */
    public function create(Request $request, EntityManagerInterface $entityManager, StatusRepository $statusRepository)
    {

        // Creation d'un nouvel event
        $event = new Event();

        // Récupération de l'utilisateur connecté
        /** @var User $user */
        $user = $this->getUser();

        // L'utilisateur connecté est défini comme organisateur
        $event->setOrganiser($user);

        // On utilise le campus de l'utilisateur connecté dans le formulaire
        $event->setCampus($user->getCampus());

        // Création du formulaire
        $eventForm = $this->createForm(EventType::class, $event);

        $eventForm->handleRequest($request);

        if ($eventForm->isSubmitted()) {
            $this->havePlace($eventForm);
            if ($eventForm->isValid()) {

                // Calcul de la date de fin de l'évènement
                /** @var DateTime $startDate */
                $startDate = $event->getDateTimeStart();
                $intervalDuration = abs($event->getDuration());
                $dateTimeEnd = DateTimeHandler::dateAddMinutes($startDate, $intervalDuration);
                $event->setDateTimeEnd($dateTimeEnd);

                $place = $eventForm->get('place')->getData();
                $event->setPlace($place);

                $status = $statusRepository->findOneBy(["name" => Constantes::CREATED]);
                $event->setStatus($status);

                $entityManager->persist($event);
                $entityManager->flush();

                $this->addFlash('success', 'Votre sortie a bien été ajoutée !');

                // La sortie est "crée" si l'utilisateur clique sur "enregistrer"
                if ($eventForm->get('save')->isClicked()) {
                    return $this->redirectToRoute('main');
                }

                return $this->redirectToRoute("event_published", ['id' => $event->getId()]);
            }
        }

        return $this->render("event/create.html.twig", [
            'eventForm' => $eventForm->createView(),
            //'placeForm' => $placeForm->createView()
        ]);
    }

    /**
     * Permet de s'inscrire à un évènement
     * @Route("/evenement/inscription/{id}", name="event_registration")
     * @param $id
     * @param EventRepository $eventRepository
     * @param EntityManagerInterface $manager
     * @param FunctionsStatus $functionsStatus
     * @return Response
     */
    public function registration($id,
                                 EventRepository $eventRepository,
                                 EntityManagerInterface $manager,
                                 FunctionsStatus $functionsStatus): Response
    {

        /** @var User $user */
        $user = $this->getUser();

        //Récupération de l'évenement choisi par mon utilisateur via l'id récupérée dans l'URL
        $eventChoosen = $eventRepository->find($id);

        //Les inscrits à la sortie
        $foundParticipants = $eventChoosen->getParticipants();

        //Mise à jour du statut au moment où la personne s'inscrit
        $functionsStatus->UpdateEventStatus($eventChoosen);

        $eventStatusName = $eventChoosen->getStatus()->getName();

        switch ($eventStatusName) {

            case Constantes::CREATED :
                $this->addFlash('warning', "Cette sortie n'est pas encore publiée!");
                return $this->redirectToRoute('main');
            case Constantes::ARCHIVED :
                $this->addFlash('warning', "Cette sortie est archivée!");
                return $this->redirectToRoute('main');
            //Si sorties annulées...
            case Constantes::CANCELLED :
                $this->addFlash('warning', "Cette sortie a été annulée!");
                return $this->redirectToRoute('main');
            //Si sorties fermées à l'inscription...
            case Constantes::CLOSED :
                $this->addFlash('warning', "La date limite d'inscription est dépassée");
                return $this->redirectToRoute('main');
            //Si sorties se déroulent au moment de l'inscription...
            case Constantes::ONGOING :
                $this->addFlash('warning', "Impossible de s'inscrire, l'activité se déroule en ce moment-même!");
                return $this->redirectToRoute('main');
            //Si la sortie est déjà passée...
            case Constantes::FINISHED :
                $this->addFlash('warning', "La sortie est finie!");
                return $this->redirectToRoute('main');
            //Si le statut de la sortie est "Ouverte"...
            case Constantes::OPENED :
                //Si l'utilisateur est l'organisateur de la sortie...
                if ($eventChoosen->getOrganiser() === $user) {

                    $this->addFlash('warning', 'Vous avez crée la sortie, vous ne pouvez pas vous inscrire!');

                } //Si l'utilisateur est déjà inscrit à la sortie...
                elseif ($foundParticipants->contains($user)) {
                    $this->addFlash('warning', 'Vous êtes déjà inscrit à cette sortie!');
                } //... On vérifie que le nombre max de participants n'est pas atteint
                elseif ($eventChoosen->getParticipants()->count() >= $eventChoosen->getMaxNumberParticipants()) {
                    $this->addFlash('warning', 'Le nombre maximum de participants a été atteint!');
                } else {
                    //Si toutes les conditions sont remplies, on ajoute notre user à la sortie
                    $eventChoosen->addParticipant($user);

                    $manager->persist($eventChoosen);
                    $manager->flush();

                    $this->addFlash('success', "Vous êtes bien inscrit à la sortie!");
                }

                return $this->redirectToRoute('main');
        }

        return $this->render("event/view.html.twig", [
            "foundEvent" => $eventChoosen,
            "foundParticipants" => $foundParticipants
        ]);
    }

    /**
     * @Route("/evenement/desistement/{id}", name="event_abandonned")
     * @param $id
     * @param EventRepository $eventRepository
     * @param EntityManagerInterface $manager
     * @param FunctionsStatus $functionsStatus
     * @return Response
     */
    public function abandon($id, EventRepository $eventRepository,
                            EntityManagerInterface $manager, FunctionsStatus $functionsStatus): Response
    {
        // Récupération de l'utilisateur connecté
        /** @var User $user */
        $user = $this->getUser();

        //Récupération de l'évenement choisi par mon utilisateur via l'id récupérée dans l'URL
        $eventChoosen = $eventRepository->find($id);

        //Récupération des inscrits à la sortie
        $foundParticipants = $eventChoosen->getParticipants();

        //Mise à jour le statut de l'évenement
        $functionsStatus->UpdateEventStatus($eventChoosen);

        // Récupération du statut de l'évenement
        $eventStatusName = $eventChoosen->getStatus()->getName();

        // Si l'utilisateur est bien dans les participants et que le statut de la sortie est "ouvert
        if (($foundParticipants->contains($user) and ($eventStatusName === Constantes::OPENED or $eventStatusName === Constantes::CLOSED))) {

            $eventChoosen->removeParticipant($user);

templates/event/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annuler votre sortie

{% endblock %}

{% block body %}
    <div class="p-3 pb-md-4 mx-auto text-center">
        <h6 class="display-6 fw-normal">Annuler une sortie</h6>
    </div>

    <main class="form-cancel">

        <fieldset disabled>
            <label for="event_name">Nom de la sortie</label>
            <input type="text" class="form-control" id="event_name" placeholder="{{ foundEvent.name }}">
            <label for="event_datestart">Date de la sortie</label>
            <input type="text" class="form-control" id="event_datestart"
                   placeholder="{{ foundEvent.dateTimeStart|date('d-m-Y') }}">
            <label for="event_campus">Campus</label>
            <input type="text" class="form-control" id="event_campus" placeholder="{{ foundEvent.campus.name }}">
            <label for="event_place">Lieu</label>
            <input type="text" class="form-control" id="event_place" placeholder="{{ foundEvent.place.name }}">

        </fieldset>



            {{ form_start(eventCancellationForm) }}

            <div>
                {{ form_row(eventCancellationForm.cancellation_reason) }}
            </div>
        <div class="p-3 pb-md-4 mx-auto text-center">
            <div>
                {{ form_row(eventCancellationForm.submit) }}
            </div>

            {{ form_end(eventCancellationForm) }}
        </div>
            <div class="p-3 pb-md-4 mx-auto text-center">
                <a href="{{ path('main') }}">
                    <button class="btn text-white" id="cancel">Annuler</button>
                </a>
            </div>

    </main>

{% endblock %}

templates/event/create.html.twig
{% extends 'base.html.twig' %}


{% block title %}Créer une sortie

{% endblock %}

{% block body %}

    <script>
        window.onload = init;
    </script>

    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">

        {% if (modif is defined and event.place is not null ) %}
            <input type="hidden" name="oldPlaceId" id="oldPlaceId" value="{{ event.place.id }}">
            <input type="hidden" name="oldCityId" id="oldCityId" value="{{ event.place.city.id }}">
            <h6 class="display-6 fw-normal border-bottom">Modifier une sortie</h6>
        {% else %}
            <input type="hidden" name="oldPlaceId" id="oldPlaceId" value="0">
            <input type="hidden" name="oldPlaceId" id="oldPlaceId" value="0">
            <h6 class="display-6 fw-normal border-bottom mb-2">Créer une sortie</h6>
        {% endif %}
    </div>


    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="row align-items-md-stretch">
            <div class="col-md-6">
                <div class="h-100">

                    {{ form_start(eventForm) }}
                    <div>{{ form_row((eventForm.name)) }}</div>
                    <div>{{ form_row((eventForm.dateTimeStart)) }}</div>
                    <div>{{ form_row((eventForm.registrationDeadline)) }}</div>
                    <div class="text-danger fw-bold">COVID 19 - Les rassemblements de plus de 6 personnes sont
                        interdits
                    </div>
                    <div>{{ form_row((eventForm.maxNumberParticipants)) }}</div>
                    <div>{{ form_row((eventForm.duration)) }}</div>
                    <div>{{ form_row((eventForm.description)) }}</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class='h-100'>
                    <div>{{ form_row((eventForm.campus)) }}</div>
                    <div>{{ form_row((eventForm.city)) }}</div> {# <select id="event_city" #}

                    <div class="group">
                        <label for="{{ field_name(eventForm.place) }}">{{ form_label(eventForm.place) }} </label>
                        <select required=required name="{{ field_name(eventForm.place) }}"
                                id="{{ field_name(eventForm.place) }}" class="form-control">
                        </select>
                    </div>
                    <fieldset disabled class="mt-2">
                        <label for="streetPlace " class="mt-3">Adresse</label>
                        <div type="text" class="form-control bg-light" id="streetPlace">Non renseignée</div>
                        <label for="latitudePlace">Latitude</label>
                        <div type="text" class="form-control bg-light" id="latitudePlace">Non renseignée</div>
                        <label for="longitudePlace">Longitude</label>
                        <div type="text" class="form-control bg-light" id="longitudePlace">Non renseignée</div>
                    </fieldset>
                </div>
            </div>

            <div class="d-flex flex-wrap justify-content-center mt-5">
                <div>{{ form_row(eventForm.save) }}</div>

                {% if ((modif is not defined) or (event.status.name is same as constant('App\\Utils\\Constantes::CREATED'))) %}
                    <div>{{ form_row(eventForm.submit) }}</div>
                {% else %}
                    <div class="group">
                        <label for="{{ field_name(eventForm.submit) }}">{{ form_label(eventForm.submit) }} </label>
                        <input type="hidden" required=required name="{{ field_name(eventForm.submit) }}"
                                id="{{ field_name(eventForm.submit) }}" class="form-control">
                    </div>
                {% endif %}

                {{ form_end(eventForm) }}

                {% if (modif is defined) %}
                    <div>
                        <a href="{{ path('event_cancelled', {id:event.id}) }}">
                            <button class="btn text-white" id="btnCancel">Supprimer la sortie</button>
                        </a>
                    </div>
                {% endif %}
                <div class="ml-3" id="cancel"><a href="{{ path('main') }}">
                        <button class="btn text-white">Annuler</button>
                    </a></div>
            </div>
        </div>
        {{ form_end(eventForm) }}
    </div>
    <script>
        updatePlaceField();
    </script>

    {# Formulaire à décommenter pour pouvoir ajouter un nouveau lieu
    {{ form_start(placeForm) }}
    {{ form_row((placeForm.name)) }}
    {{ form_row((placeForm.street)) }}
    {{ form_row ((placeForm.city )) }}
    {{ form_row((placeForm.latitude)) }}
    {{ form_row((placeForm.longitude)) }}
    {{ form_row(((placeForm.submit))) }}
    {{ form_end(placeForm) }} #}

{% endblock %}

templates/event/view.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1 class="mt-5">{{ foundEvent.name }}</h1>
    <p class="fs-5 col-md-8">{{ foundEvent.description }}</p>

    <hr class="col-3 col-md-2 mb-4">

    {% if (foundEvent.cancellationReason) %}

        <div class="p-1 mb-3 bg-danger text-white rounded-3">
            <div class="container-fluid py-5">
            <p class="col-md-8 fs-7">Sortie annulée par l'organisateur : "{{ foundEvent.cancellationReason }}" </p>
        </div>
    </div>
    {% endif %}

    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-5 bg-light border rounded-3">
                <h3>Détails de la sortie</h3>
                <br>
                <p>Campus : {{ foundEvent.campus.name }}</p>
                <p>Date et heure de la sortie : {{ foundEvent.dateTimeStart|date('d-m-Y H:i:s') }}</p>
                <p>Date limite d'inscription : {{ foundEvent.registrationDeadline|date('d-m-Y H:i:s') }}</p>
                <p>Nombres de places : {{ foundEvent.maxNumberParticipants }} </p>
                <p>Durée : {{ foundEvent.duration }} minutes </p>
                <a href="{{ path('event_registration', {id:foundEvent.id}) }}">

                    {# Si le statut n'est pas "Ouverte" on bloque #}
                    {# Si tu es organisateur on bloque #}
                    {# Si le nombre de participants est atteint "complet" #}

                    {% if(foundEvent.status.name == constant('App\\Utils\\Constantes::OPENED') and
                          foundEvent.organiser != app.user and
                          foundEvent.participants.count != foundEvent.maxNumberParticipants and
                          not foundEvent.participants.contains(app.user))  %}

                        <button class="btn-success btn mt-2">S'inscrire</button>
                    {#
                    {% elseif(foundEvent.organiser == app.user
                              and date(foundEvent.dateTimeStart) > date())
                    %}

                        <button class="btn-success btn mt-2">Annuler</button>

                    {% elseif(foundEvent.participants.contains(app.user)) %}
                        <button class="btn-success btn mt-2">Se désister</button>
                    #}
                    {% endif %}

                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5 bg-light border rounded-3">
                <h3>Accès</h3>
                <br>
                <p>Lieu : {{ foundEvent.place.name }} </p>
                <p>Rue : {{ foundEvent.place.street }} </p>
                <p>Ville : {{ foundEvent.place.city.postCode }}  {{ foundEvent.place.city.name }} </p>

                <p>Latitude : {{  foundEvent.place.latitude }}</p>
                <p>Longitude : {{  foundEvent.place.longitude }}</p>
            </div>
        </div>
    </div>

    <br>

    <h6 class="border-bottom pb-2 mb-0">Participants</h6>

    {% for participant in foundParticipants  %}
        <div class="d-flex text-muted pt-3">
        <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
            <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
                <div class="d-flex justify-content-between">
                    <strong class="text-gray-dark">{{ participant.firstName }} {{ participant.lastName }}</strong>
                    <a href="{{ path('profil_view', {'id': participant.id }) }}">Voir Profil</a>
                </div>
                <span class="d-block">{{ participant.pseudo }}</span>
            </div>
        </div>
{%  endfor %}



{% endblock %}

{% block title %} {{ foundEvent.name }}

{% endblock %}